mqtt:
  enabled: True
  host: mosquitto.mosquitto

go2rtc:
  streams:
    front:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.8.99:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.8.99:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    front2:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.8.98:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front2_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.8.98:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14
      mode: motion

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          roles:
            - detect
    onvif:
      host: 192.168.8.99
      port: 80
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"
    detect:
      enabled: true
    record: 
      enabled: true
    objects:
      track:
        - cat
        - dog
        - person
    zones:
      privacy:
        coordinates: 0.424,0.195,0,0.51,0,1,0.712,1,0.812,0.322
        loitering_time: 0
        objects:
          - person
    motion:
      mask: 0.794,0.033,0.793,0.083,0.979,0.088,0.98,0.031
    review:
      alerts:
        required_zones: privacy
  front2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front2_sub
          roles:
            - detect
    onvif:
      host: 192.168.8.98
      port: 80
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"
    detect:
      enabled: true
    record: 
      enabled: true
    objects:
      track:
        - cat
        - dog
        - person
    zones:
      privacy:
        coordinates: 1,0.462,0.678,0.19,0.302,0.02,0.072,0,0,0,0,0.333,0,1,1,1
        loitering_time: 0
        objects:
          - person
    motion:
      mask: 0.88,0.035,0.88,0.084,0.971,0.083,0.968,0.034
    review:
      alerts:
        required_zones: privacy
