namespace: radarr
commonLabels:
  app.kubernetes.io/name: radarr
commonAnnotations:
  app.kubernetes.io/name: radarr

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- storageclass.yaml