commonLabels:
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/version: 16.3.0-debian-12-r17

resources:
- statefulset.yaml
- svc.yaml

# TODO 
# change statfulset to deployment
# add pv and pvc => this will be a FS in order to readwritemany
# make the config in secrets 
