---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: Homelab overview

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
