namespace: factorio
commonLabels:
  app.kubernetes.io/name: factorio
commonAnnotations:
  app.kubernetes.io/name: factorio

secretGenerator:
- name: factorio-secret
  envs:
  - .env

resources:
- ns.yaml
- deploy.yaml
- svc.yaml
- pvc.yaml
- storageclass.yaml

