 # Let new devices join our zigbee network
permit_join: true
# Home Assistant integration (MQTT discovery)
homeassistant: true
# Docker-Compose makes the MQTT-Server available using "mqtt" hostname
# MQTT server URL
mqtt:
    base_topic: zigbee2mqtt
    server: "mqtt://mosquitto.mosquitto.svc.cluster.local:1883" # mqtt://<name_of_pod>.<name_of_namespace> (mosquitto)
# Zigbee Adapter path
serial:
    port: /dev/ttyUSB0
# Enable the Zigbee2MQTT frontend
frontend:
    port: 8080
# Let Zigbee2MQTT generate a new network key on first start
advanced:
    #network_key: GENERATE
    #log_output: ["console"]
    log_level: debug
    log_output:
    - console
    homeassistant_legacy_entity_attributes: false
    homeassistant_legacy_triggers: false
    legacy_api: false
    legacy_availability_payload: false

device_options:
  legacy: false

## Map devices to persistent /data directory
devices: /data/devices.yaml
groups: /data/groups.yaml

  