apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ai-namespace.yaml
  - ollama.yaml
  - open-webui.yaml
  - openclaw-crds.yaml
  - openclaw-operator.yaml
  - openclaw.yaml
