namespace: jellyseerr
commonLabels:
  app.kubernetes.io/name: jellyseerr
commonAnnotations:
  app.kubernetes.io/name: jellyseerr

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- storageclass.yaml
- pvc.yaml