apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./serviceaccount.yaml
  - ./clusterrole.yaml
  - ./clusterrolebinding.yaml
  - ./storageclass.yaml
  - ./networkpolicy.yaml
  - ./openclawinstance.yaml
  - ./ingress.yaml
