apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: frigate
  app.kubernetes.io/version: 0.14.0
  app.kubernetes.io/instance: frigate
commonAnnotations:
  app.kubernetes.io/name: frigate

namespace: frigate


resources:
- ./ns.yaml
- ./deploy.yaml
- ./svc.yaml
- ./ing.yaml
- ./pvc.yaml
- ./storageclass.yaml

configMapGenerator:
- name: config
  files:
  - ./assets/config.yaml

secretGenerator:
- name: creds
  env:
   .env
